### ISSUE TITLE
summary of D8ContributingArea seems incorrect.

### ISSUE THREAD

**Issue by solomonvimal** [dtarb/TauDEM-Website#2]
Hi Nazmus @nazmussazib 
Please check this - http://hydrology.usu.edu/taudem/taudem5/help53/D8ContributingArea.html

**Comment by dtarb** [comment]
I just read this description and cannot see anything incorrect, so assume that whatever the issue was, it was corrected.  I will close, but if there is something I did not notice, please let me know.
